Repository team-xquare/v1-service-attachment, pull requests merged in 2022-12, with the labels that each got.

#6 🔀 :: (#5) 의존성 관리 및 yml 값 수정
  Dockerfile
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  buildSrc/src/main/kotlin/PluginVersions.kt
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: chore, 프로젝트 설정

#10 🔀 :: (#9) CD setting
  .github/workflows/stag-build.yaml
Labels: 프로젝트 설정

#8 🔀 :: (#7) 파일 업로드
  build.gradle.kts
  src/main/kotlin/com/xquare/v1serviceattachment/attachment/exception/FileIOInterruptedException.kt
  src/main/kotlin/com/xquare/v1serviceattachment/attachment/exception/FileInvalidExtensionException.kt
  src/main/kotlin/com/xquare/v1serviceattachment/attachment/presentation/AttachmentController.kt
  src/main/kotlin/com/xquare/v1serviceattachment/attachment/presentation/dto/request/BucketNameRequest.kt
  src/main/kotlin/com/xquare/v1serviceattachment/attachment/presentation/dto/response/UploadFileResponse.kt
  src/main/kotlin/com/xquare/v1serviceattachment/attachment/service/ImageUploadService.kt
  src/main/kotlin/com/xquare/v1serviceattachment/config/error/AttachmentException.kt
  src/main/kotlin/com/xquare/v1serviceattachment/config/error/ErrorCode.kt
  src/main/kotlin/com/xquare/v1serviceattachment/config/error/ErrorHandlingController.kt
  src/main/kotlin/com/xquare/v1serviceattachment/config/error/ErrorResponse.kt
  src/main/kotlin/com/xquare/v1serviceattachment/config/exception/InvalidServerException.kt
  src/main/kotlin/com/xquare/v1serviceattachment/config/filter/ErrorHandlingFilter.kt
  src/main/kotlin/com/xquare/v1serviceattachment/config/filter/FilterConfig.kt
  src/main/kotlin/com/xquare/v1serviceattachment/config/security/SecurityConfig.kt
  src/main/kotlin/com/xquare/v1serviceattachment/config/security/WebConfig.kt
  src/main/kotlin/com/xquare/v1serviceattachment/thirdparty/s3/AwsS3Util.kt
  src/main/resources/application.yml
Labels: 기능 추가
